<h1> Transposição e Reshaping de Arrays </h1>

In [1]:
# Importando o módulo Numpy
import numpy as np

In [3]:
array1 = np.array([[65, 23, 19], [41, 87, 10]])
array1

array([[65, 23, 19],
       [41, 87, 10]])

In [4]:
array1.T

array([[65, 41],
       [23, 87],
       [19, 10]])

In [5]:
np.transpose(array1)

array([[65, 41],
       [23, 87],
       [19, 10]])

<h2> Broadcasting </h2>

In [6]:
array2 = np.array([[33, 34, 35]])
array2.T

array([[33],
       [34],
       [35]])

In [7]:
array2.T + array2

array([[66, 67, 68],
       [67, 68, 69],
       [68, 69, 70]])

<h2> Transformando Matrizes em Arrays </h2>

In [8]:
array3 = np.array([np.arange(1,6), np.arange(10,15)])
array3

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [9]:
array3.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [10]:
array3.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

<h2> Operadores Lógicos </h2>

In [12]:
np.random.seed(100)
array4 = np.random.randint(1, 10, size = (4,4))
array4

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [13]:
np.any((array4 % 7) == 0)

False

In [14]:
np.all(array4 < 11)

True

<h2> Reshaping </h2>

In [17]:
array5 = np.arange(1,16)
array5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
array5.reshape(3, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

<h2> Adicionando uma dimensão </h2>

In [19]:
array6 = np.array([14, 15, 16])
array6

array([14, 15, 16])

In [20]:
array6 = array6[:, np.newaxis]
array6

array([[14],
       [15],
       [16]])

<h2> Ordenando o Array </h2>

In [21]:
array7 = np.array([[3,2], [10, -1]])
array7

array([[ 3,  2],
       [10, -1]])

In [22]:
# Orndenando por linhas
array7.sort(axis = 1)
array7

array([[ 2,  3],
       [-1, 10]])

In [23]:
array8 = np.array([[3,2], [10, -1]])
array8

array([[ 3,  2],
       [10, -1]])

In [24]:
# Ordenando por colunas
array8.sort(axis = 0)
array8

array([[ 3, -1],
       [10,  2]])