<h1> List Comprehension </h1>
<br>
A utilização de list comprehension em Python é muito comum. List comprehension é uuma forma de Python utiliza para realizar filtros e mapeamentos semelhante ao que vimos com as funções filter() e map().

In [18]:
import numpy as np

In [1]:
# Definindo um array com a função built-in range()
array1 = range(0, 15)

In [2]:
print(array1)

range(0, 15)


In [3]:
type(array1)

range

In [5]:
# Aplicando list comprehension
[item ** 3 for item in array1]

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000, 1331, 1728, 2197, 2744]

In [6]:
[item for item in array1 if item % 2 == 0]

[0, 2, 4, 6, 8, 10, 12, 14]

In [7]:
[item ** 2 for item in array1 if item % 2 == 0]

[0, 4, 16, 36, 64, 100, 144, 196]

In [8]:
# Lista de frases
lista_frases = ['Big Data', 'Machine Learning em Big Data e Algoritmos em Big Data', 
                'Data Science e Big Data', 'Big Data e Internet das Coisas',
               'Big Data está revolucionando o mundo, pois Big Data é um grande volume de dados']

In [9]:
[item for item in lista_frases if item.count('Big Data') >= 2]

['Machine Learning em Big Data e Algoritmos em Big Data',
 'Big Data está revolucionando o mundo, pois Big Data é um grande volume de dados']

In [10]:
[float(item) for item in array1]

[0.0,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 14.0]

<h1> Funções Lambda </h1>
<br>
Funções lambda são funções anônimas que não precisam ser definidas antes de serem usadas. São também chamadas funções inline e ajudam a manter seu código mais organizado.

In [11]:
# Definindo um array com a função built-in range()
array1 = range(0, 15)

In [12]:
# Aplicando list comprehension
[item ** 2 for item in array1]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [13]:
# Definindo uma função
def square(num):
    return num ** 2

In [14]:
# Aplicando a função map()
list(map(square, array1))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [15]:
# Função lambda
list(map(lambda num: num ** 2, array1))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [16]:
list(map(lambda a: a**2, filter(lambda a: a % 2 == 0, range(1,20))))

[4, 16, 36, 64, 100, 144, 196, 256, 324]

<h1>Concatenando Arrays </h1>

In [19]:
array1 = np.ones(4)

In [20]:
array2 = np.arange(15)

In [21]:
array_conc = np.concatenate((array1, array2))

In [22]:
array_conc

array([ 1.,  1.,  1.,  1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
        9., 10., 11., 12., 13., 14.])

<h1>Joining Arrays

In [26]:
a = np.ones((3,3))
b = np.zeros((3,3))

In [27]:
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
# Primeiro preenche as linhas
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
# Primeiro preenche as colunas
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [30]:
# Joining arrays
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])

In [31]:
np.column_stack((a,b,c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [33]:
np.row_stack((a,b,c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<h1> Split Arrays