<h1> NumPy </h1>
<br>
NumPy oferece sequências de elementos que são mais eficientes que sequências padrões em Python.

In [1]:
import sys
import numpy as np
print(sys.version)
np.__version__

3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]


'1.20.3'

<h1> Concatenando Arrays </h1>

In [2]:
array1 = np.ones(4)

In [3]:
array2 = np.arange(15)

In [4]:
array_conc = np.concatenate((array1, array2))

In [5]:
array_conc

array([ 1.,  1.,  1.,  1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
        9., 10., 11., 12., 13., 14.])

<h1> Joining Arrays </h1>

In [6]:
a = np.ones((3,3))
b = np.zeros((3,3))

In [7]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Primeiro preenche as linhas
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# Primeiro preenche as colunas
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [11]:
# Joining arrays
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])

In [12]:
np.column_stack((a,b,c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [13]:
np.row_stack((a,b,c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<h1> Split Arrays </h1>

In [14]:
array3 = np.arange(16).reshape((4,4))
array3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
[array3_p1, array3_p2] = np.hsplit(array3, 2)

In [16]:
array3_p1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [17]:
array3_p2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [22]:
[array3_p1, array3_p2] = np.vsplit(array3, 2)

In [23]:
array3_p1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
array3_p2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

<h1> Gravando e Carregando Dados com NumPy </h1>

In [26]:
dados = array3

In [27]:
np.save('dados_saved_v1', dados)

In [28]:
loaded_data = np.load('dados_saved_v1.npy')

In [29]:
loaded_data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])