<h1>NumPy</h1>
<br>
<br>
<h2> Arrays NumPy - objetos multidimensionais com N dimensões </h2>
<br>
<h2> Matrizes NumPy - objetos estritamente com 2 dimensões.</h2>
<br>
A principal vantagem de utilizar matrizes em NumPy é que este tipo de objeto possui convenientes notações para multiplicação de matrizes. Arrays e Matrizes NumPy possuem o atibuto .T para retornar a transposta da matriz, enquanto objetos do tipo matriz possuem adicionalmente atribuos .I (inversa) e .H (Transposta COnjugada).

Existem diferenças em operações de álgebra lienar entre arrays e matrizes.
Muitas funções NumPy retornam arrays e não matrizes como objeto resultante.

In [1]:
import sys
import numpy as np

<h1>Criando Matrizes</h1>

In [4]:
mat1 = np.matrix("1,2,3; 4,5,6")
print(mat1)

[[1 2 3]
 [4 5 6]]


In [5]:
type(mat1)

numpy.matrix

In [6]:
mat2 = np.matrix([[1,2,3], [4,5,6]])
print(mat2)

[[1 2 3]
 [4 5 6]]


In [8]:
mat3 = np.matrix([ [0, 10, 0, 0, 0], [0, 0, 20, 0, 0], [0,0,0,30,0], [0,0,0,0,40], [0,0,0,0,0] ])
print(mat3)

[[ 0 10  0  0  0]
 [ 0  0 20  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 40]
 [ 0  0  0  0  0]]


In [9]:
mat3[2,3]

30

<h1> Matriz Esparsa </h1>
<br>
Uma matriz esparsa possui uma grande quantidade de elementos que valem zero (ou não presentes, ou não necessários). Matrizes esparsas têm aplicações em problemas de engenharia, física(por exemplo, o método de malhas para resolução de circuitos elétricos ou sistemas de equações lineares). Também têm aplicação em computação, como por exemplo em tecnologias do armazenamento de dados.

A matriz esparsa é implementada através de um conjunto de listas ligadas que apontam para elementos diferentes de zero. De forma que os elementos possuem valor zero não são armazenados.

In [10]:
import scipy.sparse

In [11]:
linhas = np.array([0,1,2,3])
colunas = np.array([1,2,3,4])
valores = np.array([10,20,30,40])

In [13]:
mat4 = scipy.sparse.coo_matrix((valores, (linhas, colunas)))
print(mat4)

  (0, 1)	10
  (1, 2)	20
  (2, 3)	30
  (3, 4)	40


In [14]:
print(mat4.todense())

[[ 0 10  0  0  0]
 [ 0  0 20  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 40]]


In [15]:
scipy.sparse.isspmatrix_coo(mat4)

True

<h1> Operações com Arrays e Matrizes </h1>

In [16]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [17]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [18]:
A = np.mat(a)
A

matrix([[1, 2],
        [3, 4]])

In [19]:
A * A

matrix([[ 7, 10],
        [15, 22]])

In [20]:
np.dot(a, a)

array([[ 7, 10],
       [15, 22]])

In [21]:
# convertendo um Array para uma Matriz
mat5 = np.asmatrix(a)
mat5

matrix([[1, 2],
        [3, 4]])

In [22]:
mat5 * mat5

matrix([[ 7, 10],
        [15, 22]])

In [24]:
# Convertendo uma Matriz para Array
array2 = np.asarray(mat5)
array2

array([[1, 2],
       [3, 4]])

In [25]:
array2 * array2

array([[ 1,  4],
       [ 9, 16]])